### ISSUE TITLE
How do I shut off Futuruscope?

### ISSUE THREAD

**Issue by joshco** [codegram/hyperclient#102]
How can I tell hyperclient to either not use futuroscope or to stop using a thread pool?
In production i can see the use of it, but in development debugging it makes it near impossible to step through what is going on.

**Comment by dblock** [comment]
It's a good question, maybe you want to open an issue/question with Futuroscope? I'd love this to be documented here.

**Comment by joshco** [comment]
Here's where I got to.  
https://github.com/codegram/futuroscope#disabling-concurrency
But when I try to reference the Futuroscope::Pools::NoPool.new, I get uninitialized constant.

Issue opened https://github.com/codegram/futuroscope/issues/25

**Comment by dblock** [comment]
Aren't they saying that all you have to do is `Futuroscope.default_pool = Futuroscope::Pools::NoPool.new`?

**Comment by joshco** [comment]
It does appear that is what they are saying but i cant figure out how to require the needed file where the pools are defined. 
(I tried it from rails console to figure out what i need to but in my classes)
Am i an idiot or something?

**Comment by dblock** [comment]
It looks like it was added in https://github.com/codegram/futuroscope/pull/22, which hasn't been released.

**Comment by joshco** [comment]
FYI Ive been using that PR and it is working eg no pool

**Comment by ivoanjo** [comment]
I believe that after #109 was merged, this can be closed.

**Comment by dblock** [comment]
Yup, thx.
