### ISSUE TITLE
Add auto-pagination of embedded items

### ISSUE THREAD

**Issue by joshco** [codegram/hyperclient#106]
Any guidance on the best practices for supporting paging (next links) with hyperclient?

**Comment by dblock** [comment]
Hyperclient just "does it", as long as the server returns `next` links. 

Server-side we use offsets and a cursor with mongoid with help from https://github.com/mongoid/mongoid-scroll and this:

```ruby
      module CursorHelpers
        extend ActiveSupport::Concern

        # apply cursor-based pagination to a collection
        # returns a hash:
        #   results: (paginated collection subset)
        #   next: (cursor to the next page)
        def paginate_by_cursor(coll, &_block)
          fail 'Both cursor and offset parameters are present, these are mutually exclusive.' if params.key?(:offset) && params.key?(:cursor)
          results = { results: [], next: nil }
          size = (params[:size] || 5).to_i
          if params.key?(:offset)
            skip = params[:offset].to_i
            coll = coll.skip(skip)
          end
          # some items may be skipped with a block
          query = block_given? ? coll : coll.limit(size)
          query.scroll(params[:cursor]) do |record, next_cursor|
            record = yield(record) if block_given?
            results[:results] << record if record
            results[:next] = next_cursor.to_s
            break if results[:results].count >= size
          end
          results[:total_count] = coll.count if params[:total_count] && coll.respond_to?(:count)
          results
        end
```

You need a paginated presenter like https://github.com/ruby-grape/grape-with-roar/blob/master/api/presenters/paginated_presenter.rb called from a presenter of models like https://github.com/ruby-grape/grape-with-roar/blob/master/api/presenters/splines_presenter.rb. 

That project doesn't do offsets and uses Kaminari like https://github.com/ruby-grape/grape-with-roar/blob/master/api/splines_endpoint.rb#L58.

**Comment by dblock** [comment]
@joshco If you want to practice, you could add cursor-based pagination in grape-with-roar, either on top of [ActiveRecord](https://github.com/ruby-grape/grape-with-roar/tree/with-activerecord) or [MongoDB](https://github.com/ruby-grape/grape-with-roar/issues/7).

**Comment by joshco** [comment]
Could you give an example of the client code using hyperclient to enumerate a paged collection?
The server side of my project does return next links, However, I was not getting beyond the first page when using code with a typical resources.each do |r| loop.

**Comment by dblock** [comment]
I was bored, so I made the MongoDB server-side example in https://github.com/ruby-grape/grape-with-roar/pull/8.

**Comment by dblock** [comment]
You still have to follow `_next` links to get everything.

```ruby
splines = client.splines
while splines
  splines._embedded.splines.each do |spline|
    puts "spline #{spline.id} #{spline.reticulated ? 'is' : 'is not'} reticulated"
  end
  
  break unless splines._links[:next]
  splines = splines._links.next
end
```

**Comment by dblock** [comment]
I'm reopening this with a new title. I think we can auto-paginate resources by default.

**Comment by dblock** [comment]
I have an implementation in https://github.com/codegram/hyperclient/pull/193, curious what people think.
