### ISSUE TITLE
hyperclient v0.8.3 breaks compatibility with Faraday < v0.9

### ISSUE THREAD

**Issue by a-maas** [codegram/hyperclient#117]
Hyperclient v0.8.3 implements [FlatParamsEncoder](https://github.com/codegram/hyperclient/blob/master/CHANGELOG.md#083-march-30-2017), which was implemented in Faraday v0.9 and above. This breaks compatibility with Faraday less than v0.9. I wanted to see if this change was intensional, and is so, if you'd consider adding the minimum version of faraday in your [gemspec](https://github.com/codegram/hyperclient/blob/master/hyperclient.gemspec#L17) so that bundler can figure out what version of hyperclient to use based on the app's version of Faraday.

**Comment by ivoanjo** [comment]
Yes, you're absolutely right! The `FlatParamsEncoder` is required, otherwise in parameters would be dropped in some cases --- when there were more than a value for the same parameter.

I will update the `gemspec` and put out a new release, thanks for reporting.

**Comment by a-maas** [comment]
Thanks!
