### ISSUE TITLE
Async background requests with futuroscope have not been async since 2014

### ISSUE THREAD

**Issue by ivoanjo** [codegram/hyperclient#123]
While working on #122 I started wondering if [`Link#http_method`](https://github.com/codegram/hyperclient/blob/master/lib/hyperclient/link.rb#L168-L181) was correct when using the `Futuroscope::Future`:

```ruby
    def http_method(method, body = nil)
      @resource = begin
        response =
          if @entry_point.options[:async]
            Futuroscope::Future.new do
              @entry_point.connection.run_request(method, _url, body, nil)
            end
          else
            @entry_point.connection.run_request(method, _url, body, nil)
          end

        Resource.new(response.body, @entry_point, response)
      end
    end
```

More specifically, we create a new `Futuroscope::Future`, store it in `response`, but then immediately ask for it's `resource.body` when creating a new resource. This means that we basically block the current thread while waiting for the future to resolve so we can call `body` on it. After the request finishes executing in the background, we finally get the `body`, and are able to create an return the new `Resource`.

Looking at git history, this has been broken since the `Resource` was introduced in 5de6f84074ac9818268e57dfad4e468a2bf4b318, which was released in version 0.6 in 2014.

So this means that for all of almost three years nobody really noticed that this was broken, which leads me to make some observations:

* Would it make sense for `async: false` to be the default behavior instead, since that's how people have been using it for a long time?
* Would it make sense to consider removing the background/async functionality altogether? 
* Alternatively, would it make sense to consider replacing futuroscope using the [`concurrent-ruby`](https://rubygems.org/gems/concurrent-ruby) which has been adopted by the likes of `activesupport`, `dry-*`, `graphql`, `hanami`, `rom`, `sidekiq`, etc. and thus most ruby applications probably already have it as a direct or indirect dependency?

**Comment by joshco** [comment]
I've run into pain due to futuroscope when debugging.  The threadpool mucks up the abilility to get decent stack traces.  I ended up setting the default pool to essentially be synchronous.
It's interesting to learn that it wasn't really providing async anyway.  Hooray for complexity without the gain :)

I don't know how much async would really help, since it's acting as a HAL client.  Since HAL depends on links and discoverability, I find that most of my requests need to be sequential anyway.

**Comment by ivoanjo** [comment]
Agreed, the `async` does have an impact on performance and your debug ability; the main reason why I added the option to turn it off is that I was working on a system which did lots of processing in parallel (with JRuby) using threads, so we did not need hyperclient to add more threads to the mix.

On the other hand, I can see it being useful if you want to, for instance, fire off several requests as a performance optimization before starting your work: that way if each request takes 1s, you go down from n seconds to 1 second, assuming the server handles it well. We also considered using it on the system I was discussing but our performance was already good enough that we never went for the extra gain.

**Comment by dblock** [comment]
Personally I find the whole futuroscope business unnecessarily complicated.

**Comment by dblock** [comment]
I've PRed https://github.com/codegram/hyperclient/pull/133 removing futuroscope. I'd like some +1 or -1 comments please. 

One of the more recent issues that we found in production was that Futuroscope alone was adding 500MB to every Sidekiq worker's RAM usage, which was an unpleasant surprise.

**Comment by ivoanjo** [comment]
Sounds like our friend [`MALLOC_ARENA_MAX`](https://devcenter.heroku.com/articles/tuning-glibc-memory-behavior) making an appearance!

Will review it asap!
