### ISSUE TITLE
EntryPoint#connection allows you to set faraday middleware after setting the adapter

### ISSUE THREAD

**Issue by composerinteralia** [codegram/hyperclient#138]
When passing a block to `client.connection` without the `default: false` option, adding any middleware will cause a warning:

```rb
api = Hyperclient.new('https://grape-with-roar.herokuapp.com/api') do |client| 
  client.connection do |conn| 
    conn.request :retry, max: 10, interval: 1.0, interval_randomness: 0.5
  end
end

api.splines

#=> WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.
```

This warning was introduced in https://github.com/lostisland/faraday/pull/685. We are seeing it here because the [default_faraday_block](https://github.com/codegram/hyperclient/blob/088f376595527792d5e28c799aed3cd4e923ef10/lib/hyperclient/entry_point.rb#L135-L144), which adds the adapter, always [runs before the custom block](https://github.com/codegram/hyperclient/blob/088f376595527792d5e28c799aed3cd4e923ef10/lib/hyperclient/entry_point.rb#L64-L65).

---

As a workaround I am specifying `default: false` and then copying in the default_faraday_block into my custom block so I can put things in the correct order:

```rb
api = Hyperclient.new('https://grape-with-roar.herokuapp.com/api') do |client| 
  client.connection(default: false) do |conn| 
    conn.use Faraday::Response::RaiseError
    conn.use FaradayMiddleware::FollowRedirects
    conn.request :hal_json
    conn.response :hal_json, content_type: /\bjson$/
    conn.request :retry, max: 10, interval: 1.0, interval_randomness: 0.5
    conn.adapter :net_http
    conn.options.params_encoder = Faraday::FlatParamsEncoder
  end
end

api.splines
```

---

Faraday Version: 0.15.4
Hyperclient Version: 0.9.0

**Comment by dblock** [comment]
Care to contribute this to README in some capacity?

**Comment by composerinteralia** [comment]
It looks like https://github.com/codegram/hyperclient/pull/149 might solve this

**Comment by dblock** [comment]
Yep, and in #163 I reworked this test.

**Comment by dblock** [comment]
This is fixed moving forward with Faraday 1+ I believe. Via https://travis-ci.org/github/codegram/hyperclient/builds/687209666:

* Faraday 0.9, no warning
* Faraday 0.17, WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.
* Faraday 1.0.1, no warning
