### ISSUE TITLE
faraday_digestauth incompatible with Faraday 1.0+

### ISSUE THREAD

**Issue by dblock** [codegram/hyperclient#161]
I made a mistake releasing Hyperclient 0.9.2 requiring https://github.com/bhaberer/faraday-digestauth >= 0.3.0 [here](https://github.com/codegram/hyperclient/blob/master/hyperclient.gemspec#L18), but that one still has faraday ~> 0.7, which now breaks anyone using hyperclient.

I yanked 0.9.2, and we need https://github.com/bhaberer/faraday-digestauth/issues/15 before this can be fixed.

**Comment by jonallured** [comment]
Bumped into this today doing my Monday morning bundle update on Convection, so I think for now one should lock their faraday to like so, right?

```ruby
# Gemfile
gem 'hyperclient'
gem 'faraday', '< 1'
```

**Comment by dblock** [comment]
Or use `gem 'bhaberer/faraday-digestauth'` in Gemfile.

**Comment by dblock** [comment]
This was resolved and 0.9.3 was cut.

I'm also fixing the build in https://github.com/codegram/hyperclient/pull/163/files.
