### ISSUE TITLE
Hyper edit

### ISSUE THREAD

**Issue by mosboomu** [codegram/hyperclient#168]
https://github.com/codegram/hyperclient/blob/ed9a79670305e10bb136bd6c3e7214bcb12f1d32/lib/hyperclient/link.rb#L84-L91

**Comment by mosboomu** [comment]
> https://github.com/codegram/hyperclient/blob/ed9a79670305e10bb136bd6c3e7214bcb12f1d32/lib/hyperclient/link.rb#L84-L91

**Comment by dblock** [comment]
@mosboomu What are you trying to do?
