### ISSUE TITLE
Using Hyperclient? Add to the wiki, please!

### ISSUE THREAD

**Issue by dblock** [codegram/hyperclient#71]
Add your project to the wiki: https://github.com/codegram/hyperclient/wiki

**Comment by ivoanjo** [comment]
Would it make sense to move this to the `README`?

**Comment by dblock** [comment]
I would add a separate .md page like USERS.md, requires a PR unlike a wiki but is more discoverable, but so be it.

**Comment by ivoanjo** [comment]
I was thinking more along the lines of moving this "issue" to the README. I'll prepare a PR with it, see what you think :)

**Comment by ivoanjo** [comment]
What do you think of https://github.com/codegram/hyperclient/pull/125?
