### ISSUE TITLE
Rename Hyperclient to HyperClient?

### ISSUE THREAD

**Issue by dblock** [codegram/hyperclient#74]
_Hyperclient_ is spelled with a lowercase c, but in some places, like in the description of this repo and in .gemspec it says _HyperClient_. While we're making backwards incompatible changes all over the place, curious what @oriolgual and others think about doing the rename into HyperClient? I personally always try to spell it this way.

**Comment by ivoanjo** [comment]
It seems like the `gemspec` is the one remaining place where `HyperClient` is used, so probably the simplest would be to fix that and close this issue?

**Comment by dblock** [comment]
Yes please @ivoanjo
