### ISSUE TITLE
Content type hal+json doesn't agree with Faraday MIME json type

### ISSUE THREAD

**Issue by dylanfareed** [codegram/hyperclient#82]
If you are making a request from a spec with setup that is something like this

```ruby
Hyperclient.new('http://example.org/') do |client|
      client.connection(default: false) do |conn|
        conn.request :json
        conn.response :json
        conn.use Faraday::Adapter::Rack, app
      end
    end
```

[FaradayMiddleware::EncodeJson](https://github.com/lostisland/faraday_middleware/blob/master/lib/faraday_middleware/request/encode_json.rb) will not convert the request to json because it isn't aware of 'application/hal+json'

We monkeypatched it locally to work around the problem but it still isn't pretty.
 
```ruby
module FaradayMiddleware
  class EncodeJson < Faraday::Middleware
    MIME_TYPE = 'application/hal+json'.freeze
  end
end
```

Alternatively, resetting the client's content type to application/json will work.

```ruby
Hyperclient.new('http://example.org/') do |client|
      client.headers['Content-Type'] = 'application/json'
      client.connection(default: false) do |conn|
        conn.request :json
        conn.response :json
        conn.use Faraday::Adapter::Rack, app
      end
    end
```

**Comment by dblock** [comment]
This was introduced in https://github.com/codegram/hyperclient/pull/81.

**Comment by dylanfareed** [comment]
Ahhh. Alternatively one can upgrade and change the connection.request thusly:

```ruby 
Hyperclient.new('http://example.org/') do |client|
      client.connection(default: false) do |conn|
        conn.request :hal_json
        conn.response :json
        conn.use Faraday::Adapter::Rack, app
      end
    end
```

**Comment by dblock** [comment]
@dylanfareed Would appreciate a PR into [UPGRADING](https://github.com/codegram/hyperclient/blob/master/UPGRADING.md) that describes the problem and solution.

**Comment by dylanfareed** [comment]
On it.

**Comment by dblock** [comment]
Closing, as properly documented in UPGRADING.
