### ISSUE TITLE
Add method fetch for Hyperclient::Resource

### ISSUE THREAD

**Issue by alabeduarte** [codegram/hyperclient#89]
Hi all,

Sometimes I use the [Hyperclient::Resource#[]](https://github.com/codegram/hyperclient/blob/master/lib/hyperclient/resource.rb#L56) as a hash, but I would like to avoid if statements when the attribute does not exist for some reason.

Did you consider implement the method fetch with similar behaviour of [Hash#fetch](http://docs.ruby-lang.org/en/2.2.0/Hash.html#method-i-fetch) in ruby?

Thanks!

**Comment by alabeduarte** [comment]
Just sent a [pull request](https://github.com/codegram/hyperclient/pull/90).

**Comment by dblock** [comment]
Closed via https://github.com/codegram/hyperclient/pull/90.
