### ISSUE TITLE
#87 has introduced a regression in shortcuts in x._embedded.x

### ISSUE THREAD

**Issue by dblock** [codegram/hyperclient#95]
The change in #87 to fix some eager skipping of links may have caused a regression. See https://github.com/dblock/slack-gamebot/commit/a14831031d5f67f2b7819837c1683143f2371856. The `.count` method is not being delegated to a fetched embedded collection anymore.

**Comment by dylanfareed** [comment]
It looks like its now being delegated to the resource attributes?

**Comment by dblock** [comment]
Released in 0.7.2.

**Comment by dblock** [comment]
Permanently fixed in 0.8.2.
